import { existsSync } from 'node:fs'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const check = process.argv.includes('--check')
const generated = '/** Generated by scripts/build.mjs. Do not edit directly. */\n'

async function output(path, body) {
  if (check) {
    if (!existsSync(path) || await readFile(path, 'utf8') !== body) {
      throw new Error(`Generated artifact is stale: ${path}`)
    }
    return
  }
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, body, 'utf8')
}

const template = (await readFile(resolve(root, 'src/client-template.js'), 'utf8')).replace(/\r\n?/gu, '\n')
async function client(adapter, destination) {
  const entry = (await readFile(resolve(root, `src/client-${adapter}-adapter.js`), 'utf8')).replace(/\r\n?/gu, '\n')
  const body = `${template.trimEnd()}\n\n${entry}`.split('\n')
    .map(line => line.trim().length === 0 ? '' : `    ${line}`).join('\n')
  await output(destination, `${generated}window.__ModuleLoader__.load({\n  id: "dsh-plugin-trace-insight",\n  factory: (require) => {\n    var module = { exports: {} };\n    var exports = module.exports;\n${body}\n    return module.exports;\n  },\n});\n`)
}

await client('sidebar', resolve(root, 'client.js'))
const standardRoot = resolve(root, 'packages/standard')
if (existsSync(resolve(standardRoot, 'package.json'))) {
  const standard = JSON.parse(await readFile(resolve(standardRoot, 'package.json'), 'utf8'))
  await client('standard', resolve(standardRoot, 'client.js'))
  const host = (await readFile(resolve(root, 'index.js'), 'utf8')).replace(/\r\n?/gu, '\n').replaceAll("'./src/", "'./lib/")
  await output(resolve(standardRoot, 'index.js'), generated + host)
  for (const filename of (await readdir(resolve(root, 'src'))).filter(name => name.endsWith('.mjs')).sort()) {
    const body = filename === 'version.mjs'
      ? `export const TRACE_INSIGHT_SERVICE_VERSION = ${JSON.stringify(standard.version)}\n`
      : (await readFile(resolve(root, 'src', filename), 'utf8')).replace(/\r\n?/gu, '\n')
    await output(resolve(standardRoot, 'lib', filename), generated + body)
  }
  await output(resolve(standardRoot, 'LICENSE'), (await readFile(resolve(root, 'LICENSE'), 'utf8')).replace(/\r\n?/gu, '\n'))
}
console.log(check ? 'Generated artifacts are current.' : 'Built sidebar and available standard artifacts.')
