import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const templatePath = resolve(root, 'src/client-template.js')
const outputPath = resolve(root, 'client.js')

const template = await readFile(templatePath, 'utf8')
const indentedBody = template
  .split('\n')
  .map(line => line.trim().length === 0 ? '' : `    ${line}`)
  .join('\n')
const wrapped = `/** Generated by scripts/build.mjs. Do not edit directly. */\nwindow.__ModuleLoader__.load({\n  id: "dsh-plugin-trace-insight",\n  factory: (require) => {\n    var module = { exports: {} };\n    var exports = module.exports;\n${indentedBody}\n    return module.exports;\n  },\n});\n`
await writeFile(outputPath, wrapped, 'utf8')
console.log(`built ${outputPath}`)
